# Generated by Django 3.2.8 on 2021-12-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='uncategorised', on_delete=django.db.models.deletion.PROTECT, related_name='blog_categories', to='blog.category'),
        ),
    ]
